package model;

public enum Action {
    GET_ACTIVITY_BY_ID,
    ADD_ACTIVITY,
    Notification,
    UPDATE_ACTIVITY,
    DELETE_ACTIVITY,
    GET_ACTIVITIES,
    GET_USER_BY_ID,
    ADD_USER,
    UPDATE_USER,
    DELETE_USER,
    GET_USERS,
    GET_USER_BY_USERNAME_AND_PASSWORD,
    GET_ACTIVITY_BY_NAME,
    GET_ACTIVITY_BY_LOCATION,
    GET_ACTIVITY_BY_CATEGORY,
    GET_ACTIVITY_BY_NAME_AND_LOCATION,
    UNREGISTER
}